Repository RedHatCloudForms/cfme-cloud_services, pull requests merged in 2019-07, with the labels that each got.

#10 Change collector to support deep nested relations
  lib/cfme/cloud_services/data_collector.rb
  spec/data_collector_spec.rb
Labels: enhancement

#14 Allow for multiple providers per provider type
  lib/cfme/cloud_services/data_collector.rb
  spec/data_collector_spec.rb
Labels: enhancement

#9 Add ems_extensions and ems_licenses to payload
  lib/cfme/cloud_services/data_collector.rb
Labels: enhancement

#22 Add Hosts, EmsClusters, and Storages to manifest
  lib/cfme/cloud_services/data_collector.rb
Labels: enhancement

#25 Cache the manifest file to reduce REST API calls
  lib/cfme/cloud_services/manifest_fetcher.rb
  spec/inventory_sync_spec.rb
Labels: enhancement

#26 Enhancing API to support sync_all and sync_platform
  app/controllers/api/red_hat_cloud_service_providers_controller.rb
  app/controllers/api/red_hat_cloud_services_controller.rb
  app/javascript/packs/red_hat_cloud_services_list.jsx
  config/api.yml
  spec/requests/red_hat_cloud_service_providers_spec.rb
  spec/requests/red_hat_cloud_services_spec.rb
Labels: enhancement, ivanchuk/yes

#34 [IVANCHUK] Change travis to run only with ruby 2.5.3
  .travis.yml
Labels: test
