Repository RedHatCloudForms/cfme-cloud_services, pull requests merged in 2019-08, with the labels that each got.

#29 Show Active menu items correctly
  app/controllers/red_hat_cloud_services_controller.rb
  lib/cfme/cloud_services/engine.rb
Labels: bug, changelog/yes, ivanchuk/yes

#31 Allow settings to override the verify_ssl param
  config/settings.yml
  lib/cfme/cloud_services/manifest_fetcher.rb
  spec/manifest_fetcher_spec.rb
Labels: enhancement

#35 Raise error when there is issue on endpoint in ManifestFest
  lib/cfme/cloud_services/manifest_fetcher.rb
  spec/manifest_fetcher_spec.rb
Labels: enhancement, ivanchuk/yes

#36 Add missing gettext annotations
  app/javascript/packs/red_hat_cloud_services_list.jsx
  app/javascript/packs/red_hat_cloud_services_redirect.jsx
Labels: internationalization, ivanchuk/yes

#40 Filter out password fields from the manifest
  lib/cfme/cloud_services/manifest_fetcher.rb
Labels: ivanchuk/yes

#41 Fix an integer overflow error for large files
  lib/cfme/cloud_services/data_packager.rb
Labels: bug, ivanchuk/yes

#42 Allow file permissions to be set by caller
  lib/cfme/cloud_services/data_packager.rb
  lib/cfme/cloud_services/inventory_sync.rb
Labels: ivanchuk/yes

#43 Add ip address to context data
  lib/cfme/cloud_services/inventory_sync.rb
Labels: enhancement
